### ISSUE TITLE
Question: Testing services - calling original functions

### ISSUE THREAD

**Issue by dbabaioff** [ofirdagan/tada#3]
Let's say a want to test factory "A", and this factory has 2 functions:

``` js
angular.module('app').factory('A', function() {
    return {
        func1: function() {
            return func2();
        },
        funct2: function() {
            return 'TEST';
       }
    };
})
.factory('AMock', function(tadaUtils) {
    return {
        func1: tadaUtils.createFunc('func1'),
        func2: tadaUtils.createFunc('func2')
    };
});
```

If I mock the factory "A":

``` js
var A;

beforeEach(function() {
    module(function (tadaUtilsProvider) {
        tadaUtilsProvider.mock('A');
    });

    inject(function(_A_) {
        A = _A_;
    }
});
```

How can I test for example func1, how can I call the original "A.func1" function?

``` js
it('...', function() {
    A.func1(); // How can access this function, If I replaced the factory A with a mocked version, using (tadaUtilsProvider.mock - $provide)

    expect(A.func2).toHaveBeenCalled();
});
```

**Comment by ofirdagan** [comment]
Hi @dbabaioff  , I'm sorry for the long delay. From some reason the github mail reached my spam folder.. Now it's fixed.

Regarding your question..  The test that actually tests "A" factory should not use tada. Instead you should inject the real "A" factory and test its logic.

The idea of tada is to supply a simple interface to write maintainable test kits for your components and for writing more organized and descriptive tests.

You would want to use your "AMock" when u will want to test a different component that uses "A". Then u will not care about "A" inner logic because it has already been tested in "A" test. Instead you would just want to tell the test what func1/func2 supposed to return.

Please let me know if It's not clear or I missed understand your question

**Comment by dbabaioff** [comment]
Thanks @ofirdagan! Now I understand better..
You guys using this library on WIX?

**Comment by ofirdagan** [comment]
Yup

**Comment by dbabaioff** [comment]
:+1:
